version: "3"

services:
  app:
    image: node:14.18.1-alpine
    volumes:
      - .:/app
    container_name: nuxt
    working_dir: /app
    ports:
      - 80:3000
    environment:
      HOST: 0.0.0.0
    command: "npm run dev"